FROM golang:1.17-buster

ARG version=v4.31.0

RUN git clone https://github.com/v2fly/v2ray-core.git v2ray && cd v2ray && git checkout ${version}
WORKDIR v2ray
RUN CGO_ENABLE=0 go build -o v2ray -trimpath -a -tags netgo -ldflags "-s -w -buildid=" ./main
RUN CGO_ENABLED=0 go build -o v2ctl -trimpath -a -tags netgo -tags confonly -ldflags "-s -w -buildid=" ./infra/control/main

FROM alpine:3.12

COPY --from=0 /go/v2ray/v2ray /bin/
COPY --from=0 /go/v2ray/v2ctl /bin/


