name: build-latest-tag

on:
  schedule:
    - cron: '0 16 * * *' 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: get latest tag
        id: get_latest_tag
        run: |
          ./get_latest_tag.sh
