name: build-latest-tag

on:
  schedule:
    - cron: '0 16 * * *' 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: get latest tag
        id: get_latest_tag
        run: |
          tagname=`curl "https://github.com/XTLS/Xray-core/releases" 2>&1 | grep "tree" | grep "data-view-component"  | head -n 1 | awk -F"\"" '{print $2}' | awk -F"/" '{print $5}'`
          echo "get tagname:${{tagname}}"
          echo "::set-output name=latest_tag::${{ tagname }}"
