name: xray-core-build-latest-tag

on:
  schedule:
    - cron: '0 5,17 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: get latest tag
        id: get_latest_tag
        run: |
          ./get_latest_tag.sh 'XTLS/Xray-core'
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.xray
          build-args: version=${{ steps.get_latest_tag.outputs.LATEST_TAG_NAME }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7,linux/arm/v6
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/xray-core:${{ steps.get_latest_tag.outputs.LATEST_TAG_NAME }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/xray-core:latest
