name: xray-core-build-by-tag

on:
  push:
    tags:
      - 'v*'
      - '!v*-preview'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Get current tag 
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Test get tag
        run: echo "current tag:${{ env.tag }}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: VERSION=${{ env.tag }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/xray-core:${{ env.tag }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/xray-core:latest
